spring:
  application:
    name: bankai

  datasource:
    url: ENC(+Hw47OHHBD4u0hgOUM8Ui4vzWD8AwvEo9XRFIzys8rzZiSxYuzE9C5vESDHGflK6FGkSaTv3fQKHyZm/yzLtlznZS2jpG1AwtkvhTtvfm3rT2rnVZt0XMw==)
    username: ENC(5coC5RV8Dpf6qeHKDrKZuQ==)
    password: ENC(KDewUoWvVTcbeORnql1WAnmlB8USs29f)

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000