spring:
  application:
    name: bankai
  data:
    redis:
      host: localhost # 퍼블릭 IPv4 주소
      port: 6379
      password: aaaa # 서버 redis 비밀번호

  datasource:
    url: ENC(+Hw47OHHBD4u0hgOUM8Ui4vzWD8AwvEo9XRFIzys8rzZiSxYuzE9C5vESDHGflK6FGkSaTv3fQKHyZm/yzLtlznZS2jpG1AwtkvhTtvfm3rT2rnVZt0XMw==)
    username: ENC(5coC5RV8Dpf6qeHKDrKZuQ==)
    password: ENC(KDewUoWvVTcbeORnql1WAnmlB8USs29f)

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000
  jwt:
    secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa
